storage: /verdaccio/storage

store:
  s3-storage-example:
    bucket: my.unique.bucket.name
    keyPrefix: docker-test-prefix
    region: eu-west-2
    endpoint: http://localstack-s3:5002

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $all
    proxy: npmjs
  '**':
    access: $all
    publish: $all
    proxy: npmjs

logs:
  - {type: stdout, format: pretty, level: trace}

listen:
  - 0.0.0.0:4873